// Post-build prerender: renders every route with the SSR bundle and writes a
// static HTML file per route containing the real content + per-route <head>.
//
// Pipeline (see package.json "build"):
//   1. vite build                     -> dist/ (client assets + shell template)
//   2. vite build --ssr entry-server  -> dist-ssr/entry-server.js (render fn)
//   3. node scripts/prerender.mjs      -> dist/<route>.html (this file)
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const distDir = resolve(root, "dist");
const ssrEntry = resolve(root, "dist-ssr/entry-server.js");

const { render, PRERENDER_ROUTES } = await import(pathToFileURL(ssrEntry).href);

const ROUTES = PRERENDER_ROUTES ?? [
  "/",
  "/mentions-legales",
  "/confidentialite",
  "/cookies",
];

const template = readFileSync(resolve(distDir, "index.html"), "utf8");

function routeToFile(route) {
  const clean = route.replace(/^\/+/, "").replace(/\/+$/, "");
  return clean === "" ? "index.html" : `${clean}.html`;
}

let count = 0;
for (const route of ROUTES) {
  const { appHtml, helmet } = render(route);

  const headTags = helmet
    ? [
        helmet.title.toString(),
        helmet.meta.toString(),
        helmet.link.toString(),
        helmet.script.toString(),
      ]
        .filter(Boolean)
        .join("\n    ")
    : "";

  // React 19 SSR hoists <link rel="preload" as="image"> for every img src into
  // the body stream. Strip all of them to avoid dozens of below-fold preloads
  // that hurt CWV. The hero/LCP image (logo-intro) uses fetchpriority="high"
  // which the browser handles natively — no manual preload needed.
  const cleanedAppHtml = appHtml.replace(
    /<link[^>]+rel="preload"[^>]+as="image"[^>]*>/g,
    "",
  );

  const html = template
    // Drop the static fallback <title> so Helmet's per-route title is the only one.
    .replace(/\s*<title>[\s\S]*?<\/title>/, "")
    .replace("</head>", `    ${headTags}\n  </head>`)
    .replace('<div id="root"></div>', `<div id="root">${cleanedAppHtml}</div>`);

  const file = routeToFile(route);
  writeFileSync(resolve(distDir, file), html, "utf8");
  const title = helmet?.title.toString().replace(/<[^>]+>/g, "") ?? "(none)";
  console.log(
    `[prerender] ${route.padEnd(20)} -> dist/${file.padEnd(24)} | ${title}`,
  );
  count++;
}

// Generate dist/sitemap.xml from the prerendered route list so it never drifts
// from the actual pages, with <lastmod> stamped to the real build date.
const SITE_URL = "https://www.archi-made.com";
const LEGAL = new Set(["/mentions-legales", "/confidentialite", "/cookies"]);
const sitemapMeta = (route) => {
  if (route === "/") return { changefreq: "monthly", priority: "1.0" };
  if (LEGAL.has(route)) return { changefreq: "yearly", priority: "0.3" };
  // service + location silo pages
  return { changefreq: "monthly", priority: "0.8" };
};
{
  const buildDate = new Date().toISOString().slice(0, 10);
  const urls = ROUTES.map((route) => {
    const loc = route === "/" ? `${SITE_URL}/` : `${SITE_URL}${route}`;
    const { changefreq, priority } = sitemapMeta(route);
    return [
      "  <url>",
      `    <loc>${loc}</loc>`,
      `    <lastmod>${buildDate}</lastmod>`,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      "  </url>",
    ].join("\n");
  }).join("\n");
  const sitemap =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by scripts/prerender.mjs from PRERENDER_ROUTES (src/App.tsx). Do not edit by hand. -->\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${urls}\n` +
    `</urlset>\n`;
  writeFileSync(resolve(distDir, "sitemap.xml"), sitemap, "utf8");
  console.log(
    `[prerender] sitemap.xml -> ${ROUTES.length} URLs (lastmod ${buildDate})`,
  );
}

// The SSR bundle is a build artifact only; don't ship it.
rmSync(resolve(root, "dist-ssr"), { recursive: true, force: true });
console.log(`[prerender] done: ${count} route(s) written.`);
